---
version: "3.8"
services:

    test_web:
        build:
            context: .
            dockerfile: web/Dockerfile
        environment:
            AISCORE_HOST: aiscore_app
        image: aiscore_web
        networks:
            - microservices
        ports:
            - 5000:5000

    test_app:
        build:
            context: .
            dockerfile: app/Dockerfile
        image: aiscore_app
        networks:
            - microservices
networks:
    microservices: